---
title: "Agriculture land"
author: "Devin McCormack"
date: "1/23/2018"
output: html_document
data source: https://www.gapminder.org/data/
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## percent agricultural land in 

```{r}
library(ggplot2)
getwd()
setwd('../lesson4')
list.files()
agri<-read.csv("agriculture land.csv")
```
## basic EDA for graphing

```{r}
summary(agri)
```
Notes: there are NAs, and that there are a bunch of years. This isn't "tidy" data.

```{r}
library(tidyverse)

tidyagri<-gather(agri,"year","percent",2:53,na.rm=TRUE)
  
tidyagri$year<-as.numeric(gsub("[^0-9]","",tidyagri$year))
rename(tidyagri,country=Agricultural.land....of.land.area.)->tidyagri
head(tidyagri)
```


```{r}
ggplot(data=subset(tidyagri,year>=1990),aes(x=percent))+
  geom_histogram(binwidth=5)+
  facet_wrap(~year,nrow=4)+
  xlab('Percent of land used for agriculture')+
  ylab('Number of Countries')
ggsave('percentHistogram.png')
```


```{r}
ggplot(data=subset(tidyagri,year%%10 %in% c(1,6)),aes(x=year,y=percent,group=year))+
  geom_boxplot()+
  xlab('Year')+
  ylab('Percent of land')
ggsave('percentbox.png')
data
```

## two variable analysis

I need to load in some more data, tidy it up and merge it with the current dataset.


```{r load in labor percent of age 15+}
list.files()
 labor<-read.csv("above 15 labour to pop percent.csv")
 summary(labor)
 length(labor)
```
```{r tidy up the labor data}
tidylabor<-gather(labor,"year","percent",2:30,na.rm=TRUE)
  
tidylabor$year<-as.numeric(gsub("[^0-9]","",tidylabor$year))

rename(tidylabor,country=Total.15..labour.to.population....)->tidylabor
head(tidylabor)
```

```{r join the two with dplyr}
agrilabor<-inner_join(tidyagri,tidylabor,by=c("year","country"),suffix=c(".area",".labor"))
head(agrilabor)
```

```{r}
ggplot(data=agrilabor,aes(x=percent.area,y=percent.labor,color=year))+
  geom_point(alpha=1/10)
```

## Multiple variables

load in third dataset, exports as percentage of GDP


```{r load in exports}
list.files()
 exports<-read.csv("Exports_percent_GDP.csv")
 summary(exports)
head(exports)
```


### tidy it up

```{r tidy up the export data}
tidyexport<-gather(exports,"year","percent",2:52,na.rm=TRUE)
  
tidyexport$year<-as.numeric(gsub("[^0-9]","",tidyexport$year))

rename(tidyexport,country=Exports.of.goods.and.services....of.GDP.)->tidyexport
tidyexport
```


```{r again join with dplyr}
inner_join(agrilabor,tidyexport,by=c("year","country"))%>%
  rename(percent.export=percent)%>%
  mutate(decade=cut(year,breaks=c(1979,1990,2000,2007)))->agrilaborexp
agrilaborexp
```


```{r plot colored}
ggplot(data=agrilaborexp,aes(x=percent.area,color=percent.labor,y=percent.export))+
  geom_point(alpha=1/10)+
  scale_y_log10()
```

















